<?php
/** op-layout-onepiece:/header.phtml
 *
 * @creation  2017-09-07
 * @version   1.0
 * @package   op-layout-onepiece
 * @author    Tomoaki Nagahara
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2019-02-23
 */
namespace OP;

//	...
OP()->Unit()->WebPack()->Auto('css/header.css');

?>
<header>
	<a href="<?= OP::URL('app:/') ?>"><img src="/webpack/img/onepiece.png"/></a>
	<div>
		<a href="<?= OP::URL('app:/') ?>"><span>onepiece-framework.com</span></a>
	</div>
</header>
