<?php
/** op-layout-onepiece:/html.phtml
 *
 * @creation  2017-09-07
 * @version   1.0
 * @package   op-layout-onepiece
 * @author    Tomoaki Nagahara
 * @copyright Tomoaki Nagahara All rights reserved.
 */

/** namespace
 *
 * @created   2019-02-23
 */
namespace OP;

?>
<!doctype html>
<html lang="en">
	<head>
		<?= OP::Template('layout/head.phtml') ?>
	</head>
	<body id="body" class="body" role="document">
		<div id="head-area">
			<?= OP::Template('header.phtml') ?>
		</div>
		<div id="body-area" class="body-area">
			<div id="content-area" class="content-area">
				<?= OP()->Unit()->App()->Content(); ?>
			</div>
		</div>
		<div id="foot-area">
			<?= OP::Template('footer.phtml') ?>
		</div>
	</body>
</html>
